---
- name: Adding Kubernetes repository
  yum_repository:
    name: Kubernetes
    description: repo for kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: true
    enabled: true
    repo_gpgcheck: true
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Install kubectl
  yum:
    name: kubectl
    state: latest
    update_cache: true

    