---

- name: YUM | Install rke2-agent
  yum:
    name: rke2-agent
    state: latest

- name: CIS | copy systemctl file for kernel hardening
  ansible.builtin.copy:
    src: /usr/share/rke2/rke2-cis-sysctl.conf
    dest: /etc/sysctl.d/60-rke2-cis.conf
    remote_src: true
  when: rke2_cis_mode
  register: systemctl_state
    ## TODO: add checking so we dont always restart the following service

- name: CIS | restart systemd-sysctl
  ansible.builtin.systemd:
    state: restarted
    name: systemd-sysctl
  when: systemctl_state.changed


- name: SYSTEMD | rke2-agent 
  ansible.builtin.systemd:
    name: rke2-agent
    state: started
    enabled: yes
